[feynmanium.base]
exts = [
    "feynmanium.cogs.calc",
    "feynmanium.cogs.game",
    "feynmanium.cogs.misc",
    "feynmanium.cogs.trans"
]
rdy = [
    "Feynman is wholly ready!",
    "Feynman is now waiting.",
    "Now running Feynman...",
    "Feynman is connected!",
    "INITIALIZED: FEYNMAN",
]

[feynmanium.main]
desc = """Feynman - A Discord bot that works.
This bot is created by TonyBrown148."""
ownr = [728198677050425424]
glds = [255467070777458688]

[feynmanium.cogs.calc]
five = true

[feynmanium.cogs.game]
path = "./stockfish/stockfish_14_x64"
card = [
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Strength",
    "The Hermit",
    "Wheel of Fortune",
    "Justice",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Star",
    "The Moon",
    "The Sun",
    "Judgement",
    "The World",
]

[feynmanium.cogs.misc]
err = [
    "What are you expecting me to say?",
    "What am I expected to do then?",
    "Wait what? Are you serious?",
]
stat = [
    "Try @Feynman help",
    "Send @Feynman help",
    "Type @Feynman help",
    "PREFIX = MENTION",
    "Mention me before commands",
    "My prefix is my mention",
    "with the Discord API",
    "with Python",
    "with discord.py",
]
ball = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful."
]
